# Generated by Django 6.0.2 on 2026-02-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="hire_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="phone",
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
