# Generated by Django 6.0.2 on 2026-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0002_remove_employee_address_remove_employee_employee_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("stock", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
