# Generated by Django 6.0.2 on 2026-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_sale_employee_alter_sale_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="monthly_target",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
